#! /usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')
begin
  require 'vegas'
rescue LoadError
  require 'rubygems'
  require 'vegas'
end

require 'server'
server = Qless::ShardedServer.new

server.add_instance(
  'foo-0', Qless::Client.new(:url => 'redis://localhost:6379/0'), 'foo-0/')
server.add_instance(
  'foo-1', Qless::Client.new(:url => 'redis://localhost:6379/1'), 'foo-1/')

Vegas::Runner.new(server, 'qless-sharded-web', {
  :before_run => lambda {|v|
    path = (ENV['RESQUECONFIG'] || v.args.first)
    load path.to_s.strip if path
  }
}) do |runner, opts, app|
  # opts.on('-r redis-connection', "--redis redis-connection", "set the Redis connection string") {|redis_conf|
  #   runner.logger.info "Using Redis connection '#{redis_conf}'"
  #   Resque.redis = redis_conf
  # }
end
